use_frameworks!

platform :ios, '9.0'

target 'TRUThirdFaceObjcModule_Example' do
  pod 'TRUThirdFaceObjcModule', :path => '../'
  pod 'Masonry'
  target 'TRUThirdFaceObjcModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
